const data = {
  recipes: [
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 20,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 7,
      healthScore: 17,
      creditsText: "foodista.com",
      sourceName: "foodista.com",
      pricePerServing: 449.96,
      extendedIngredients: [
        {
          id: 1082047,
          aisle: "Spices and Seasonings",
          image: "salt.jpg",
          consistency: "SOLID",
          name: "kosher salt",
          nameClean: "kosher salt",
          original: "3/4 tsp kosher salt",
          originalName: "kosher salt",
          amount: 0.75,
          unit: "tsp",
          meta: [],
          measures: {
            us: { amount: 0.75, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 0.75, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
        {
          id: 10023567,
          aisle: "Meat",
          image: "fresh-ground-beef.jpg",
          consistency: "SOLID",
          name: "ground sirloin",
          nameClean: "ground sirloin",
          original: "1 pound(s) ground sirloin",
          originalName: "pound(s) ground sirloin",
          amount: 1,
          unit: "pounds",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "lb", unitLong: "pound" },
            metric: { amount: 453.592, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 10023567,
          aisle: "Meat",
          image: "fresh-ground-beef.jpg",
          consistency: "SOLID",
          name: "ground sirloin",
          nameClean: "ground sirloin",
          original: "1/2 pound ground Sirloin",
          originalName: "ground Sirloin",
          amount: 0.5,
          unit: "pound",
          meta: [],
          measures: {
            us: { amount: 0.5, unitShort: "lb", unitLong: "pounds" },
            metric: { amount: 226.796, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 18079,
          aisle: "Pasta and Rice",
          image: "breadcrumbs.jpg",
          consistency: "SOLID",
          name: "bread crumbs",
          nameClean: "breadcrumbs",
          original: "1/4 cup dry bread Crumbs",
          originalName: "dry bread Crumbs",
          amount: 0.25,
          unit: "cup",
          meta: ["dry"],
          measures: {
            us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 59.147,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 27048,
          aisle: "Condiments",
          image: "dark-sauce.jpg",
          consistency: "LIQUID",
          name: "steak sauce",
          nameClean: "steak sauce",
          original: "1/2 cup steak sauce",
          originalName: "steak sauce",
          amount: 0.5,
          unit: "cup",
          meta: [],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1123,
          aisle: "Milk, Eggs, Other Dairy",
          image: "egg.png",
          consistency: "SOLID",
          name: "egg",
          nameClean: "egg",
          original: "1 large egg",
          originalName: "egg",
          amount: 1,
          unit: "large",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "large", unitLong: "large" },
            metric: { amount: 1, unitShort: "large", unitLong: "large" },
          },
        },
        {
          id: 1002030,
          aisle: "Spices and Seasonings",
          image: "pepper.jpg",
          consistency: "SOLID",
          name: "ground pepper",
          nameClean: "black pepper",
          original: "1/2 tsp ground black pepper",
          originalName: "ground black pepper",
          amount: 0.5,
          unit: "tsp",
          meta: ["black"],
          measures: {
            us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
        {
          id: 18350,
          aisle: "Bakery/Bread",
          image: "hamburger-bun.jpg",
          consistency: "SOLID",
          name: "hamburger buns",
          nameClean: "hamburger bun",
          original: "4 hamburger buns",
          originalName: "hamburger buns",
          amount: 4,
          unit: "",
          meta: [],
          measures: {
            us: { amount: 4, unitShort: "", unitLong: "" },
            metric: { amount: 4, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 1004,
          aisle: "Cheese",
          image: "blue-cheese.png",
          consistency: "SOLID",
          name: "cheese",
          nameClean: "blue cheese",
          original: "4 ounces sliced blue cheese",
          originalName: "sliced blue cheese",
          amount: 4,
          unit: "ounces",
          meta: ["blue", "sliced"],
          measures: {
            us: { amount: 4, unitShort: "oz", unitLong: "ounces" },
            metric: { amount: 113.398, unitShort: "g", unitLong: "grams" },
          },
        },
      ],
      id: 635350,
      title: "Blue Cheese Burgers",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl: "https://www.foodista.com/recipe/ZVXPQHB5/blue-cheese-burgers",
      image: "https://spoonacular.com/recipeImages/635350-556x370.jpg",
      imageType: "jpg",
      summary:
        'You can never have too many main course recipes, so give Blue Cheese Burgers a try. This recipe serves 4. One portion of this dish contains around <b>45g of protein</b>, <b>37g of fat</b>, and a total of <b>659 calories</b>. For <b>$4.5 per serving</b>, this recipe <b>covers 28%</b> of your daily requirements of vitamins and minerals. 7 people have tried and liked this recipe. This recipe from Foodista requires egg, steak sauce, ground sirloin, and ground pepper. It is a <b>rather pricey</b> recipe for fans of American food. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 65%</b>. Try <a href="https://spoonacular.com/recipes/blue-cheese-burgers-1449231">Blue Cheese Burgers</a>, <a href="https://spoonacular.com/recipes/blue-cheese-burgers-288878">Blue Cheese Burgers</a>, and <a href="https://spoonacular.com/recipes/blue-cheese-burgers-482425">Blue Cheese Burgers</a> for similar recipes.',
      cuisines: ["American"],
      dishTypes: ["lunch", "main course", "main dish", "dinner"],
      diets: [],
      occasions: [],
      instructions:
        "Step 1: In a bowl, add chuck, sirloin, bread crumbs, steak sauce, eggs, salt, and pepper, and mix gently with fork.\nStep 2: Form 4 patties out of this mixture.\nStep 3: Cook the hamburgers patties on each side, then cover with aluminium foil.\nStep 4: Cut the sides of the bun, then grill in a stove-top grill until toasted.\nStep 5: Place patties and a slice of blue cheese in each bun.\nStep 6: Serve hot.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "In a bowl, add chuck, sirloin, bread crumbs, steak sauce, eggs, salt, and pepper, and mix gently with fork.",
              ingredients: [
                {
                  id: 18079,
                  name: "breadcrumbs",
                  localizedName: "breadcrumbs",
                  image: "breadcrumbs.jpg",
                },
                {
                  id: 27048,
                  name: "steak sauce",
                  localizedName: "steak sauce",
                  image: "dark-sauce.jpg",
                },
                {
                  id: 10023003,
                  name: "porterhouse steak",
                  localizedName: "porterhouse steak",
                  image: "tbone-or-porterhouse-raw.jpg",
                },
                {
                  id: 1002030,
                  name: "pepper",
                  localizedName: "pepper",
                  image: "pepper.jpg",
                },
                {
                  id: 1123,
                  name: "egg",
                  localizedName: "egg",
                  image: "egg.png",
                },
                {
                  id: 2047,
                  name: "salt",
                  localizedName: "salt",
                  image: "salt.jpg",
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image: "bowl.jpg",
                },
              ],
            },
            {
              number: 2,
              step: "Form 4 patties out of this mixture.",
              ingredients: [],
              equipment: [],
            },
            {
              number: 3,
              step: "Cook the hamburgers patties on each side, then cover with aluminium foil.",
              ingredients: [],
              equipment: [
                {
                  id: 404765,
                  name: "aluminum foil",
                  localizedName: "aluminum foil",
                  image: "aluminum-foil.png",
                },
              ],
            },
            {
              number: 4,
              step: "Cut the sides of the bun, then grill in a stove-top grill until toasted.",
              ingredients: [
                {
                  id: 0,
                  name: "roll",
                  localizedName: "roll",
                  image: "dinner-yeast-rolls.jpg",
                },
              ],
              equipment: [
                {
                  id: 404794,
                  name: "stove",
                  localizedName: "stove",
                  image: "oven.jpg",
                },
                {
                  id: 404706,
                  name: "grill",
                  localizedName: "grill",
                  image: "grill.jpg",
                },
              ],
            },
            {
              number: 5,
              step: "Place patties and a slice of blue cheese in each bun.",
              ingredients: [
                {
                  id: 1004,
                  name: "blue cheese",
                  localizedName: "blue cheese",
                  image: "blue-cheese.png",
                },
                {
                  id: 0,
                  name: "roll",
                  localizedName: "roll",
                  image: "dinner-yeast-rolls.jpg",
                },
              ],
              equipment: [],
            },
            { number: 6, step: "Serve hot.", ingredients: [], equipment: [] },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/blue-cheese-burgers-635350",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 11,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 2,
      healthScore: 30,
      creditsText: "foodista.com",
      sourceName: "foodista.com",
      pricePerServing: 217.17,
      extendedIngredients: [
        {
          id: 5062,
          aisle: "Meat",
          image: "chicken-breasts.png",
          consistency: "SOLID",
          name: "whl chicken breasts",
          nameClean: "chicken breast",
          original: "2 whl chicken breasts",
          originalName: "whl chicken breasts",
          amount: 2,
          unit: "",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "", unitLong: "" },
            metric: { amount: 2, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 10511819,
          aisle: "Produce",
          image: "red-chili.jpg",
          consistency: "SOLID",
          name: "whl chili pepper",
          nameClean: "red chili pepper",
          original: "8 whl dried red chili pepper",
          originalName: "whl dried red chili pepper",
          amount: 8,
          unit: "",
          meta: ["dried", "red"],
          measures: {
            us: { amount: 8, unitShort: "", unitLong: "" },
            metric: { amount: 8, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 42289,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "vegetable-oil.jpg",
          consistency: "LIQUID",
          name: "corn oil",
          nameClean: "corn oil",
          original: "6 tablespoons Peanut or corn oil",
          originalName: "Peanut or corn oil",
          amount: 6,
          unit: "tablespoons",
          meta: [],
          measures: {
            us: { amount: 6, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 6, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 20027,
          aisle: "Baking",
          image: "white-powder.jpg",
          consistency: "SOLID",
          name: "cornstarch",
          nameClean: "corn starch",
          original: "1 teaspoon Cornstarch",
          originalName: "Cornstarch",
          amount: 1,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
        {
          id: 1124,
          aisle: "Milk, Eggs, Other Dairy",
          image: "egg-white.jpg",
          consistency: "SOLID",
          name: "egg white",
          nameClean: "egg whites",
          original: "1 Egg white",
          originalName: "Egg white",
          amount: 1,
          unit: "",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "", unitLong: "" },
            metric: { amount: 1, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 16092,
          aisle: "Nuts;Savory Snacks",
          image: "peanuts.png",
          consistency: "SOLID",
          name: "roasted peanuts",
          nameClean: "roasted peanuts",
          original: "1/2 cup Roasted peanuts",
          originalName: "Roasted peanuts",
          amount: 0.5,
          unit: "cup",
          meta: [],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 2047,
          aisle: "Spices and Seasonings",
          image: "salt.jpg",
          consistency: "SOLID",
          name: "salt",
          nameClean: "table salt",
          original: "salt",
          originalName: "salt",
          amount: 4,
          unit: "servings",
          meta: [],
          measures: {
            us: { amount: 4, unitShort: "servings", unitLong: "servings" },
            metric: { amount: 4, unitShort: "servings", unitLong: "servings" },
          },
        },
        {
          id: 11291,
          aisle: "Produce",
          image: "spring-onions.jpg",
          consistency: "SOLID",
          name: "scallions",
          nameClean: "spring onions",
          original: "2 Scallions, cut in 1/4 in",
          originalName: "Scallions, cut in 1/4 in",
          amount: 2,
          unit: "",
          meta: ["cut in 1/4 in"],
          measures: {
            us: { amount: 2, unitShort: "", unitLong: "" },
            metric: { amount: 2, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 4058,
          aisle: "Ethnic Foods",
          image: "sesame-oil.png",
          consistency: "LIQUID",
          name: "sesame oil",
          nameClean: "sesame oil",
          original: "1 teaspoon Sesame oil",
          originalName: "Sesame oil",
          amount: 1,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
        {
          id: 16124,
          aisle: "Ethnic Foods;Condiments",
          image: "soy-sauce.jpg",
          consistency: "LIQUID",
          name: "soy sauce",
          nameClean: "soy sauce",
          original: "2 tablespoons Soy sauce",
          originalName: "Soy sauce",
          amount: 2,
          unit: "tablespoons",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 14412,
          aisle: "Beverages",
          image: "water.png",
          consistency: "LIQUID",
          name: "water",
          nameClean: "water",
          original: "Water",
          originalName: "Water",
          amount: 4,
          unit: "servings",
          meta: [],
          measures: {
            us: { amount: 4, unitShort: "servings", unitLong: "servings" },
            metric: { amount: 4, unitShort: "servings", unitLong: "servings" },
          },
        },
        {
          id: 2053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "vinegar-(white).jpg",
          consistency: "LIQUID",
          name: "distilled vinegar",
          nameClean: "distilled white vinegar",
          original: "1 teaspoon Distilled white vinegar",
          originalName: "Distilled white vinegar",
          amount: 1,
          unit: "teaspoon",
          meta: ["white"],
          measures: {
            us: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
      ],
      id: 649131,
      title: "Kung Po Chicken",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl: "http://www.foodista.com/recipe/HDCGFZVF/kung-po-chicken",
      image: "https://spoonacular.com/recipeImages/649131-556x370.jpg",
      imageType: "jpg",
      summary:
        'If you have roughly <b>45 minutes</b> to spend in the kitchen, Kung Po Chicken might be a spectacular <b>gluten free, dairy free, and ketogenic</b> recipe to try. For <b>$2.17 per serving</b>, you get a main course that serves 4. One serving contains <b>478 calories</b>, <b>33g of protein</b>, and <b>34g of fat</b>. 2 people were impressed by this recipe. Head to the store and pick up water, cornstarch, salt, and a few other things to make it today. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 73%</b>. This score is solid. Similar recipes include <a href="https://spoonacular.com/recipes/kung-pao-popeye-kung-pao-chicken-made-with-popeyes-nuggets-1196129">Kung Pao Popeye (Kung Pao Chicken Made with Popeye\'s Nuggets)</a>, <a href="https://spoonacular.com/recipes/kung-pao-popeye-kung-pao-chicken-made-with-popeyes-nuggets-95410">Kung Pao Popeye (Kung Pao Chicken Made with Popeye\'s Nuggets)</a>, and <a href="https://spoonacular.com/recipes/kung-po-chicken-685079">Kung Po Chicken</a>.',
      cuisines: [],
      dishTypes: ["lunch", "main course", "main dish", "dinner"],
      diets: ["gluten free", "dairy free", "ketogenic"],
      occasions: [],
      instructions:
        "<ol><li>Cut chicken into 1/2 inch cubes. You will have about 1-1/2 cups. Combine the egg white, cornstarch, soy sauce and 1 tbsp water and add to chicken cubes, mixing well. Set aside for 30 minutes. Wipe the chicli peppers clean with a wet towel. Remove the tops and set aside on plate with scallions Combine the sauce ingredients in a cup. Set aside near cooking area. Place a strainer over a pot near the cooking area. Heat a wok over moderate heat until it is very hot. Add the peanut oil and heat to about 300. Mix the chicken again and add to the hot oil. Raise the heat to</li></ol>",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Cut chicken into 1/2 inch cubes. You will have about 1-1/2 cups.",
              ingredients: [
                {
                  id: 5006,
                  name: "whole chicken",
                  localizedName: "whole chicken",
                  image: "whole-chicken.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 2,
              step: "Combine the egg white, cornstarch, soy sauce and 1 tbsp water and add to chicken cubes, mixing well. Set aside for 30 minutes. Wipe the chicli peppers clean with a wet towel.",
              ingredients: [
                {
                  id: 20027,
                  name: "corn starch",
                  localizedName: "corn starch",
                  image: "white-powder.jpg",
                },
                {
                  id: 1124,
                  name: "egg whites",
                  localizedName: "egg whites",
                  image: "egg-white.jpg",
                },
                {
                  id: 16124,
                  name: "soy sauce",
                  localizedName: "soy sauce",
                  image: "soy-sauce.jpg",
                },
                {
                  id: 5006,
                  name: "whole chicken",
                  localizedName: "whole chicken",
                  image: "whole-chicken.jpg",
                },
                {
                  id: 10111333,
                  name: "peppers",
                  localizedName: "peppers",
                  image: "green-pepper.jpg",
                },
                {
                  id: 14412,
                  name: "water",
                  localizedName: "water",
                  image: "water.png",
                },
              ],
              equipment: [],
              length: { number: 30, unit: "minutes" },
            },
            {
              number: 3,
              step: "Remove the tops and set aside on plate with scallions",
              ingredients: [
                {
                  id: 11291,
                  name: "green onions",
                  localizedName: "green onions",
                  image: "spring-onions.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step: "Combine the sauce ingredients in a cup. Set aside near cooking area.",
              ingredients: [
                { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              ],
              equipment: [],
            },
            {
              number: 5,
              step: "Place a strainer over a pot near the cooking area.",
              ingredients: [],
              equipment: [
                {
                  id: 405600,
                  name: "sieve",
                  localizedName: "sieve",
                  image: "strainer.png",
                },
                {
                  id: 404752,
                  name: "pot",
                  localizedName: "pot",
                  image: "stock-pot.jpg",
                },
              ],
            },
            {
              number: 6,
              step: "Heat a wok over moderate heat until it is very hot.",
              ingredients: [],
              equipment: [
                {
                  id: 404666,
                  name: "wok",
                  localizedName: "wok",
                  image: "wok.png",
                },
              ],
            },
            {
              number: 7,
              step: "Add the peanut oil and heat to about 30",
              ingredients: [
                {
                  id: 4042,
                  name: "peanut oil",
                  localizedName: "peanut oil",
                  image: "peanut-oil.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 8,
              step: "Mix the chicken again and add to the hot oil. Raise the heat to",
              ingredients: [
                {
                  id: 5006,
                  name: "whole chicken",
                  localizedName: "whole chicken",
                  image: "whole-chicken.jpg",
                },
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl: "https://spoonacular.com/kung-po-chicken-649131",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 3,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 2,
      healthScore: 13,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 186.53,
      extendedIngredients: [
        {
          id: 1034053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "LIQUID",
          name: "extra virgin olive oil",
          nameClean: "extra virgin olive oil",
          original: "2 tablespoons extra virgin olive oil",
          originalName: "extra virgin olive oil",
          amount: 2,
          unit: "tablespoons",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 10611282,
          aisle: "Produce",
          image: "white-onion.png",
          consistency: "SOLID",
          name: "onion",
          nameClean: "white onion",
          original: "1 large white onion, chopped",
          originalName: "white onion, chopped",
          amount: 1,
          unit: "large",
          meta: ["white", "chopped"],
          measures: {
            us: { amount: 1, unitShort: "large", unitLong: "large" },
            metric: { amount: 1, unitShort: "large", unitLong: "large" },
          },
        },
        {
          id: 11821,
          aisle: "Produce",
          image: "red-pepper.jpg",
          consistency: "SOLID",
          name: "bell pepper",
          nameClean: "red pepper",
          original: "1 red bell pepper, chopped",
          originalName: "red bell pepper, chopped",
          amount: 1,
          unit: "",
          meta: ["red", "chopped"],
          measures: {
            us: { amount: 1, unitShort: "", unitLong: "" },
            metric: { amount: 1, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 11215,
          aisle: "Produce",
          image: "garlic.png",
          consistency: "SOLID",
          name: "garlic",
          nameClean: "garlic",
          original: "4-6 cloves garlic, minced",
          originalName: "garlic, minced",
          amount: 4,
          unit: "cloves",
          meta: ["minced"],
          measures: {
            us: { amount: 4, unitShort: "cloves", unitLong: "cloves" },
            metric: { amount: 4, unitShort: "cloves", unitLong: "cloves" },
          },
        },
        {
          id: 11979,
          aisle: "Canned and Jarred;Produce;Ethnic Foods",
          image: "jalapeno-pepper.png",
          consistency: "SOLID",
          name: "jalapeno peppers",
          nameClean: "jalapeno pepper",
          original: "2 jalapeno peppers, minced",
          originalName: "jalapeno peppers, minced",
          amount: 2,
          unit: "",
          meta: ["minced"],
          measures: {
            us: { amount: 2, unitShort: "", unitLong: "" },
            metric: { amount: 2, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 1012028,
          aisle: "Spices and Seasonings",
          image: "paprika.jpg",
          consistency: "SOLID",
          name: "paprika",
          nameClean: "smoked paprika",
          original: "1-2 tablespoons smoked paprika",
          originalName: "smoked paprika",
          amount: 1,
          unit: "tablespoons",
          meta: ["smoked"],
          measures: {
            us: { amount: 1, unitShort: "Tbsp", unitLong: "Tbsp" },
            metric: { amount: 1, unitShort: "Tbsp", unitLong: "Tbsp" },
          },
        },
        {
          id: 2009,
          aisle: "Spices and Seasonings",
          image: "chili-powder.jpg",
          consistency: "SOLID",
          name: "chili powder",
          nameClean: "chili powder",
          original: "2-4 teaspoons of chili powder, or more to taste",
          originalName: "chili powder, or more to taste",
          amount: 2,
          unit: "teaspoons",
          meta: ["to taste"],
          measures: {
            us: { amount: 2, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 2, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
        {
          id: 1012014,
          aisle: "Spices and Seasonings",
          image: "ground-cumin.jpg",
          consistency: "SOLID",
          name: "ground cumin",
          nameClean: "ground cumin",
          original: "2 teaspoons ground cumin",
          originalName: "ground cumin",
          amount: 2,
          unit: "teaspoons",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 2, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
        {
          id: 1002030,
          aisle: "Spices and Seasonings",
          image: "pepper.jpg",
          consistency: "SOLID",
          name: "pepper",
          nameClean: "black pepper",
          original: "1 teaspoon black pepper",
          originalName: "black pepper",
          amount: 1,
          unit: "teaspoon",
          meta: ["black"],
          measures: {
            us: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
        {
          id: 19165,
          aisle: "Baking",
          image: "cocoa-powder.png",
          consistency: "SOLID",
          name: "cocoa powder",
          nameClean: "cacao powder",
          original: "1/4 teaspoon unsweetened cocoa powder",
          originalName: "unsweetened cocoa powder",
          amount: 0.25,
          unit: "teaspoon",
          meta: ["unsweetened"],
          measures: {
            us: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
        {
          id: 5662,
          aisle: "Meat",
          image: "meat-ground.jpg",
          consistency: "SOLID",
          name: "ground turkey meat",
          nameClean: "ground turkey",
          original: "1 pound lean ground turkey meat",
          originalName: "lean ground turkey meat",
          amount: 1,
          unit: "pound",
          meta: ["lean"],
          measures: {
            us: { amount: 1, unitShort: "lb", unitLong: "pound" },
            metric: { amount: 453.592, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 10011531,
          aisle: "Canned and Jarred",
          image: "tomatoes-canned.png",
          consistency: "SOLID",
          name: "canned tomatoes",
          nameClean: "canned whole tomatoes",
          original: "1 14.5 ounce can peeled tomatoes",
          originalName: "peeled tomatoes",
          amount: 14.5,
          unit: "ounce",
          meta: ["peeled", "canned"],
          measures: {
            us: { amount: 14.5, unitShort: "oz", unitLong: "ounces" },
            metric: { amount: 411.068, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 16018,
          aisle: "Canned and Jarred",
          image: "black-beans.jpg",
          consistency: "SOLID",
          name: "black beans",
          nameClean: "canned black beans",
          original: "1 16 ounce can black beans, drained and rinsed",
          originalName: "black beans, drained and rinsed",
          amount: 16,
          unit: "ounce",
          meta: ["drained and rinsed", "canned"],
          measures: {
            us: { amount: 16, unitShort: "oz", unitLong: "ounces" },
            metric: { amount: 453.592, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 14006,
          aisle: "Alcoholic Beverages",
          image: "beer.jpg",
          consistency: "LIQUID",
          name: "beer",
          nameClean: "light beer",
          original: "1 bottle of beer (I used Miller Light)",
          originalName: "beer (I used Miller Light)",
          amount: 1,
          unit: "bottle",
          meta: ["light", "(I used Miller )"],
          measures: {
            us: { amount: 1, unitShort: "bottle", unitLong: "bottle" },
            metric: { amount: 1, unitShort: "bottle", unitLong: "bottle" },
          },
        },
        {
          id: 16424,
          aisle: "Ethnic Foods;Condiments",
          image: "soy-sauce.jpg",
          consistency: "LIQUID",
          name: "soy sauce",
          nameClean: "lower sodium soy sauce",
          original: "2 tablespoons low-sodium soy sauce",
          originalName: "low-sodium soy sauce",
          amount: 2,
          unit: "tablespoons",
          meta: ["low-sodium"],
          measures: {
            us: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 11165,
          aisle: "Produce",
          image: "cilantro.png",
          consistency: "SOLID",
          name: "cilantro",
          nameClean: "cilantro",
          original: "1 bunch of fresh cilantro, minced",
          originalName: "fresh cilantro, minced",
          amount: 1,
          unit: "bunch",
          meta: ["fresh", "minced"],
          measures: {
            us: { amount: 1, unitShort: "bunch", unitLong: "bunch" },
            metric: { amount: 1, unitShort: "bunch", unitLong: "bunch" },
          },
        },
      ],
      id: 641679,
      title: "Drunken Turkey Chili",
      readyInMinutes: 45,
      servings: 8,
      sourceUrl:
        "https://www.foodista.com/recipe/5KJFZQ7L/drunken-turkey-chili",
      image: "https://spoonacular.com/recipeImages/641679-556x370.jpg",
      imageType: "jpg",
      summary:
        'If you have roughly <b>45 minutes</b> to spend in the kitchen, Drunken Turkey Chili might be a great <b>dairy free</b> recipe to try. This recipe serves 8. For <b>$1.87 per serving</b>, this recipe <b>covers 16%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains around <b>18g of protein</b>, <b>5g of fat</b>, and a total of <b>191 calories</b>. 2 people found this recipe to be flavorful and satisfying. Head to the store and pick up jalapeno peppers, onion, beer, and a few other things to make it today. It works well as a rather inexpensive main course. Only a few people really liked this American dish. It is brought to you by Foodista. It can be enjoyed any time, but it is especially good for <b>The Super Bowl</b>. With a spoonacular <b>score of 51%</b>, this dish is solid. Try <a href="https://spoonacular.com/recipes/drunken-turkey-chili-1369719">Drunken Turkey Chili</a>, <a href="https://spoonacular.com/recipes/drunken-turkey-45708">Drunken Turkey</a>, and <a href="https://spoonacular.com/recipes/good-old-fashioned-drunken-turkey-137828">Good Old Fashioned Drunken Turkey</a> for similar recipes.',
      cuisines: ["American"],
      dishTypes: ["lunch", "soup", "main course", "main dish", "dinner"],
      diets: ["dairy free"],
      occasions: ["super bowl"],
      instructions:
        "1. Gently heat the oil in a large pot. Do not let it smoke!\n2. Add the onion, bell pepper, garlic, and jalapenos. Saute over medium heat until soft, about 5 minutes.\n3. Add all powdered spices and stir to coat vegetables.\n4. Add turkey. Saute for three or four minutes, until just cooked through. Use your spoon or spatula to break it up.\n5. Drain the juice from the peeled tomatoes into your chili pot. Then finely chop the tomatoes and add them as well. Stir.\n6. Add the black beans, the beer, and the soy sauce. Stir.\n7. Add cilantro and stir well.\n8. Cover and allow to simmer over low heat for five to ten minutes. Then turn off the heat and let it rest for about fifteen minutes before serving.\n9. Optional Garnishes: Top with low-fat sour cream, grated cheese, avocado slices, chopped green onions, or anything else that suits your fancy! I love to eat it with tortilla chips.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Gently heat the oil in a large pot. Do not let it smoke!",
              ingredients: [
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404752,
                  name: "pot",
                  localizedName: "pot",
                  image: "stock-pot.jpg",
                },
              ],
            },
            {
              number: 2,
              step: "Add the onion, bell pepper, garlic, and jalapenos.",
              ingredients: [
                {
                  id: 10211821,
                  name: "bell pepper",
                  localizedName: "bell pepper",
                  image: "bell-pepper-orange.png",
                },
                {
                  id: 11979,
                  name: "jalapeno pepper",
                  localizedName: "jalapeno pepper",
                  image: "jalapeno-pepper.png",
                },
                {
                  id: 11215,
                  name: "garlic",
                  localizedName: "garlic",
                  image: "garlic.png",
                },
                {
                  id: 11282,
                  name: "onion",
                  localizedName: "onion",
                  image: "brown-onion.png",
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: "Saute over medium heat until soft, about 5 minutes.",
              ingredients: [],
              equipment: [],
              length: { number: 5, unit: "minutes" },
            },
            {
              number: 4,
              step: "Add all powdered spices and stir to coat vegetables.",
              ingredients: [
                {
                  id: 11583,
                  name: "vegetable",
                  localizedName: "vegetable",
                  image: "mixed-vegetables.png",
                },
                {
                  id: 2035,
                  name: "spices",
                  localizedName: "spices",
                  image: "spices.png",
                },
              ],
              equipment: [],
            },
            {
              number: 5,
              step: "Add turkey.",
              ingredients: [
                {
                  id: 5165,
                  name: "whole turkey",
                  localizedName: "whole turkey",
                  image: "turkey-raw-whole.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 6,
              step: "Saute for three or four minutes, until just cooked through. Use your spoon or spatula to break it up.",
              ingredients: [],
              equipment: [
                {
                  id: 404642,
                  name: "spatula",
                  localizedName: "spatula",
                  image: "spatula-or-turner.jpg",
                },
              ],
              length: { number: 4, unit: "minutes" },
            },
            {
              number: 7,
              step: "Drain the juice from the peeled tomatoes into your chili pot. Then finely chop the tomatoes and add them as well. Stir.",
              ingredients: [
                {
                  id: 10011531,
                  name: "canned whole tomatoes",
                  localizedName: "canned whole tomatoes",
                  image: "tomatoes-canned.png",
                },
                {
                  id: 11529,
                  name: "tomato",
                  localizedName: "tomato",
                  image: "tomato.png",
                },
                {
                  id: 11819,
                  name: "chili pepper",
                  localizedName: "chili pepper",
                  image: "red-chili.jpg",
                },
                {
                  id: 1019016,
                  name: "juice",
                  localizedName: "juice",
                  image: "apple-juice.jpg",
                },
              ],
              equipment: [
                {
                  id: 404752,
                  name: "pot",
                  localizedName: "pot",
                  image: "stock-pot.jpg",
                },
              ],
            },
            {
              number: 8,
              step: "Add the black beans, the beer, and the soy sauce. Stir.",
              ingredients: [
                {
                  id: 16015,
                  name: "black beans",
                  localizedName: "black beans",
                  image: "black-beans.jpg",
                },
                {
                  id: 16124,
                  name: "soy sauce",
                  localizedName: "soy sauce",
                  image: "soy-sauce.jpg",
                },
                {
                  id: 14003,
                  name: "beer",
                  localizedName: "beer",
                  image: "beer.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 9,
              step: "Add cilantro and stir well.",
              ingredients: [
                {
                  id: 11165,
                  name: "cilantro",
                  localizedName: "cilantro",
                  image: "cilantro.png",
                },
              ],
              equipment: [],
            },
            {
              number: 10,
              step: "Cover and allow to simmer over low heat for five to ten minutes. Then turn off the heat and let it rest for about fifteen minutes before serving.",
              ingredients: [],
              equipment: [],
              length: { number: 5, unit: "minutes" },
            },
            { number: 11, step: "Optional", ingredients: [], equipment: [] },
            {
              number: 12,
              step: "Garnishes: Top with low-fat sour cream, grated cheese, avocado slices, chopped green onions, or anything else that suits your fancy! I love to eat it with tortilla chips.",
              ingredients: [
                {
                  id: 1179,
                  name: "light sour cream",
                  localizedName: "light sour cream",
                  image: "sour-cream",
                },
                {
                  id: 1019037,
                  name: "avocado slices",
                  localizedName: "avocado slices",
                  image: "avocado-slices.jpg",
                },
                {
                  id: 19056,
                  name: "tortilla chips",
                  localizedName: "tortilla chips",
                  image: "tortilla-chips.jpg",
                },
                {
                  id: 11291,
                  name: "green onions",
                  localizedName: "green onions",
                  image: "spring-onions.jpg",
                },
                {
                  id: 1041009,
                  name: "cheese",
                  localizedName: "cheese",
                  image: "cheddar-cheese.png",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/drunken-turkey-chili-641679",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: true,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: true,
      weightWatcherSmartPoints: 8,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 3,
      healthScore: 72,
      creditsText: "foodista.com",
      sourceName: "foodista.com",
      pricePerServing: 443,
      extendedIngredients: [
        {
          id: 99215,
          aisle: "Produce",
          image: "choy-sum.jpg",
          consistency: "SOLID",
          name: "yu choy",
          nameClean: "choy sum",
          original: "1 bunch Yu Choy",
          originalName: "Yu Choy",
          amount: 1,
          unit: "bunch",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "bunch", unitLong: "bunch" },
            metric: { amount: 1, unitShort: "bunch", unitLong: "bunch" },
          },
        },
        {
          id: 19334,
          aisle: "Baking",
          image: "light-brown-sugar.jpg",
          consistency: "SOLID",
          name: "brown sugar",
          nameClean: "golden brown sugar",
          original: "1/4 cup Brown Sugar",
          originalName: "Brown Sugar",
          amount: 0.25,
          unit: "cup",
          meta: [],
          measures: {
            us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 59.147,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 6972,
          aisle: "Ethnic Foods",
          image: "tomato-sauce-or-pasta-sauce.jpg",
          consistency: "SOLID",
          name: "chili sauce",
          nameClean: "chili sauce",
          original: "1 teaspoon Hot Chili Sauce",
          originalName: "Hot Chili Sauce",
          amount: 1,
          unit: "teaspoon",
          meta: ["hot"],
          measures: {
            us: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
        {
          id: 6179,
          aisle: "Ethnic Foods",
          image: "asian-fish-sauce.jpg",
          consistency: "LIQUID",
          name: "fish sauce",
          nameClean: "fish sauce",
          original: "2 tablespoons Fish Sauce",
          originalName: "Fish Sauce",
          amount: 2,
          unit: "tablespoons",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 10211216,
          aisle: "Produce",
          image: "ginger.png",
          consistency: "SOLID",
          name: "ginger",
          nameClean: "fresh ginger",
          original: "2 tablespoons Minced Fresh Ginger",
          originalName: "Minced Fresh Ginger",
          amount: 2,
          unit: "tablespoons",
          meta: ["fresh", "minced"],
          measures: {
            us: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 2043,
          aisle: "Spices and Seasonings",
          image: "turmeric.jpg",
          consistency: "SOLID",
          name: "ground turmeric",
          nameClean: "turmeric",
          original: "1 tablespoon ground Dried Turmeric",
          originalName: "ground Dried Turmeric",
          amount: 1,
          unit: "tablespoon",
          meta: ["dried"],
          measures: {
            us: { amount: 1, unitShort: "Tbsp", unitLong: "Tbsp" },
            metric: { amount: 1, unitShort: "Tbsp", unitLong: "Tbsp" },
          },
        },
        {
          id: 9159,
          aisle: "Produce",
          image: "lime.jpg",
          consistency: "SOLID",
          name: "lime",
          nameClean: "lime",
          original: "1 Lime",
          originalName: "Lime",
          amount: 1,
          unit: "",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "", unitLong: "" },
            metric: { amount: 1, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 10115076,
          aisle: "Seafood",
          image: "salmon.png",
          consistency: "SOLID",
          name: "salmon fillet",
          nameClean: "salmon fillets",
          original: "1 1/2 pounds Salmon Fillet",
          originalName: "Salmon Fillet",
          amount: 1.5,
          unit: "pounds",
          meta: [],
          measures: {
            us: { amount: 1.5, unitShort: "lb", unitLong: "pounds" },
            metric: { amount: 680.389, unitShort: "g", unitLong: "grams" },
          },
        },
      ],
      id: 663157,
      title: "Thai Street Vendor Salmon Skewers",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        "http://www.foodista.com/recipe/YKLGHHWH/thai-street-vendor-salmon-skewers",
      image: "https://spoonacular.com/recipeImages/663157-556x370.jpg",
      imageType: "jpg",
      summary:
        'Thai Street Vendor Salmon Skewers takes roughly <b>45 minutes</b> from beginning to end. This main course has <b>324 calories</b>, <b>36g of protein</b>, and <b>11g of fat</b> per serving. This recipe serves 4 and costs $4.43 per serving. 3 people were impressed by this recipe. This recipe from Foodista requires ginger, ground turmeric, lime, and fish sauce. It is a good option if you\'re following a <b>gluten free, dairy free, fodmap friendly, and pescatarian</b> diet. It is a <b>pretty expensive</b> recipe for fans of Asian food. Taking all factors into account, this recipe <b>earns a spoonacular score of 94%</b>, which is outstanding. <a href="https://spoonacular.com/recipes/thai-street-vendor-salmon-skewers-1259215">Thai Street Vendor Salmon Skewers</a>, <a href="https://spoonacular.com/recipes/persian-street-vendor-kebabs-97763">Persian Street Vendor Kebabs</a>, and <a href="https://spoonacular.com/recipes/thai-street-chicken-707949">Thai Street Chicken</a> are very similar to this recipe.',
      cuisines: ["Thai", "Asian"],
      dishTypes: ["lunch", "main course", "main dish", "dinner"],
      diets: ["gluten free", "dairy free", "fodmap friendly", "pescatarian"],
      occasions: [],
      instructions:
        '<ol><li>Remove skin from salmon fillet and trim away any brown fatty areas.</li><li>Place 8 bamboo skewers into the fillet running from the thick side to the thin about 1.5 inches apart. Then slice the fillet so that you have individual pieces of salmon on the skewers.</li><li>Make a sauce combining the remaining ingredients, including the juice from the lime and the zest. It\'s also easiest to mince the ginger by putting it through a garlic press. You can adjust the mix of ingredients to match your personal tastes.</li><li>Place the salmon in a deep bowl or ziploc bag and marinate in about half of the sauce, reserving the rest for serving. Refrigerate for 30 minutes to an hour, more will break down the fish and cause it to "cook" a bit in the lime juice.</li><li>Grill skewers on a high heat and serve. Eat with chilled raw Yu Choy, which you use to wrap bits of the fish and drizzle with remaining sauce.</li></ol>',
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Remove skin from salmon fillet and trim away any brown fatty areas.",
              ingredients: [
                {
                  id: 10115076,
                  name: "salmon fillets",
                  localizedName: "salmon fillets",
                  image: "salmon.png",
                },
              ],
              equipment: [],
            },
            {
              number: 2,
              step: "Place 8 bamboo skewers into the fillet running from the thick side to the thin about 1.5 inches apart. Then slice the fillet so that you have individual pieces of salmon on the skewers.Make a sauce combining the remaining ingredients, including the juice from the lime and the zest. It's also easiest to mince the ginger by putting it through a garlic press. You can adjust the mix of ingredients to match your personal tastes.",
              ingredients: [
                {
                  id: 11215,
                  name: "garlic",
                  localizedName: "garlic",
                  image: "garlic.png",
                },
                {
                  id: 11216,
                  name: "ginger",
                  localizedName: "ginger",
                  image: "ginger.png",
                },
                {
                  id: 15076,
                  name: "salmon",
                  localizedName: "salmon",
                  image: "salmon.png",
                },
                {
                  id: 1019016,
                  name: "juice",
                  localizedName: "juice",
                  image: "apple-juice.jpg",
                },
                {
                  id: 0,
                  name: "ground meat",
                  localizedName: "ground meat",
                  image: "fresh-ground-beef.jpg",
                },
                { id: 0, name: "sauce", localizedName: "sauce", image: "" },
                {
                  id: 9159,
                  name: "lime",
                  localizedName: "lime",
                  image: "lime.jpg",
                },
              ],
              equipment: [
                {
                  id: 404627,
                  name: "garlic press",
                  localizedName: "garlic press",
                  image: "garlic-press.jpg",
                },
                {
                  id: 3065,
                  name: "skewers",
                  localizedName: "skewers",
                  image: "wooden-skewers.jpg",
                },
              ],
            },
            {
              number: 3,
              step: 'Place the salmon in a deep bowl or ziploc bag and marinate in about half of the sauce, reserving the rest for serving. Refrigerate for 30 minutes to an hour, more will break down the fish and cause it to "cook" a bit in the lime juice.Grill skewers on a high heat and serve. Eat with chilled raw Yu Choy, which you use to wrap bits of the fish and drizzle with remaining sauce.',
              ingredients: [
                {
                  id: 9160,
                  name: "lime juice",
                  localizedName: "lime juice",
                  image: "lime-juice.png",
                },
                {
                  id: 15076,
                  name: "salmon",
                  localizedName: "salmon",
                  image: "salmon.png",
                },
                { id: 0, name: "sauce", localizedName: "sauce", image: "" },
                {
                  id: 10115261,
                  name: "fish",
                  localizedName: "fish",
                  image: "fish-fillet.jpg",
                },
                {
                  id: 10018364,
                  name: "wrap",
                  localizedName: "wrap",
                  image: "flour-tortilla.jpg",
                },
              ],
              equipment: [
                {
                  id: 3065,
                  name: "skewers",
                  localizedName: "skewers",
                  image: "wooden-skewers.jpg",
                },
                {
                  id: 404706,
                  name: "grill",
                  localizedName: "grill",
                  image: "grill.jpg",
                },
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image: "bowl.jpg",
                },
              ],
              length: { number: 30, unit: "minutes" },
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/thai-street-vendor-salmon-skewers-663157",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: true,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 5,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 551,
      healthScore: 10,
      creditsText: "blogspot.com",
      sourceName: "blogspot.com",
      pricePerServing: 141.29,
      extendedIngredients: [
        {
          id: 10123,
          aisle: "Meat",
          image: "raw-bacon.png",
          consistency: "SOLID",
          name: "bacon",
          nameClean: "applewood smoked bacon",
          original: "2 strips bacon (optional)",
          originalName: "bacon (optional)",
          amount: 2,
          unit: "strips",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "strips", unitLong: "strips" },
            metric: { amount: 2, unitShort: "strips", unitLong: "strips" },
          },
        },
        {
          id: 11215,
          aisle: "Produce",
          image: "garlic.png",
          consistency: "SOLID",
          name: "garlic",
          nameClean: "garlic",
          original: "1 clove garlic, minced",
          originalName: "garlic, minced",
          amount: 1,
          unit: "clove",
          meta: ["minced"],
          measures: {
            us: { amount: 1, unitShort: "clove", unitLong: "clove" },
            metric: { amount: 1, unitShort: "clove", unitLong: "clove" },
          },
        },
        {
          id: 1004,
          aisle: "Cheese",
          image: "blue-cheese.png",
          consistency: "SOLID",
          name: "gorgonzola",
          nameClean: "blue cheese",
          original: "2/3c crumbled Gorgonzola* (or other blue cheese)",
          originalName: "crumbled Gorgonzola* (or other blue cheese)",
          amount: 0.6666667,
          unit: "c",
          meta: ["blue", "crumbled", "(or other cheese)"],
          measures: {
            us: { amount: 0.667, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 157.725,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 10111529,
          aisle: "Produce",
          image: "cherry-tomatoes.png",
          consistency: "SOLID",
          name: "grape tomatoes",
          nameClean: "grape tomato",
          original: "1/2 cup chopped grape tomatoes",
          originalName: "chopped grape tomatoes",
          amount: 0.5,
          unit: "cup",
          meta: ["chopped"],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1034053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "LIQUID",
          name: "grapeseed oil",
          nameClean: "extra virgin olive oil",
          original: "1 tsp extra virgin olive oil or grapeseed oil",
          originalName: "extra virgin olive oil or grapeseed oil",
          amount: 1,
          unit: "tsp",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
        {
          id: 11109,
          aisle: "Produce",
          image: "cabbage.jpg",
          consistency: "SOLID",
          name: "cabbage",
          nameClean: "cabbage",
          original: "1/2 head green cabbage, tough outer leaves removed",
          originalName: "green cabbage, tough outer leaves removed",
          amount: 0.5,
          unit: "head",
          meta: ["green"],
          measures: {
            us: { amount: 0.5, unitShort: "head", unitLong: "heads" },
            metric: { amount: 0.5, unitShort: "head", unitLong: "heads" },
          },
        },
        {
          id: 9152,
          aisle: "Produce",
          image: "lemon-juice.jpg",
          consistency: "LIQUID",
          name: "juice of lemon",
          nameClean: "lemon juice",
          original: "juice of 1/2 lemon",
          originalName: "juice lemon",
          amount: 0.5,
          unit: "",
          meta: [],
          measures: {
            us: { amount: 0.5, unitShort: "", unitLong: "" },
            metric: { amount: 0.5, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 1001256,
          aisle: "Milk, Eggs, Other Dairy",
          image: "white-cream.png",
          consistency: "LIQUID",
          name: "greek yogurt",
          nameClean: "plain greek yogurt",
          original: "1 cup plain Greek yogurt",
          originalName: "plain Greek yogurt",
          amount: 1,
          unit: "cup",
          meta: ["plain"],
          measures: {
            us: { amount: 1, unitShort: "cup", unitLong: "cup" },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1102047,
          aisle: "Spices and Seasonings",
          image: "salt-and-pepper.jpg",
          consistency: "SOLID",
          name: "salt and pepper",
          nameClean: "salt and pepper",
          original: "salt and freshly-ground pepper",
          originalName: "salt and freshly-ground pepper",
          amount: 4,
          unit: "servings",
          meta: ["freshly-ground"],
          measures: {
            us: { amount: 4, unitShort: "servings", unitLong: "servings" },
            metric: { amount: 4, unitShort: "servings", unitLong: "servings" },
          },
        },
        {
          id: 11291,
          aisle: "Produce",
          image: "spring-onions.jpg",
          consistency: "SOLID",
          name: "scallions",
          nameClean: "spring onions",
          original: "1-2T chopped scallions",
          originalName: "chopped scallions",
          amount: 1,
          unit: "T",
          meta: ["chopped"],
          measures: {
            us: { amount: 1, unitShort: "Tbsp", unitLong: "Tbsp" },
            metric: { amount: 1, unitShort: "Tbsp", unitLong: "Tbsp" },
          },
        },
        {
          id: 11291,
          aisle: "Produce",
          image: "spring-onions.jpg",
          consistency: "SOLID",
          name: "scallions",
          nameClean: "spring onions",
          original: "2T chopped scallions",
          originalName: "chopped scallions",
          amount: 2,
          unit: "T",
          meta: ["chopped"],
          measures: {
            us: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
      ],
      id: 716430,
      title: "Roasted Cabbage Wedge Salad with Yogurt Gorgonzola Dressing",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        "http://fullbellysisters.blogspot.com/2012/03/roasted-cabbage-wedge-salad-with-yogurt.html",
      image: "https://spoonacular.com/recipeImages/716430-556x370.jpg",
      imageType: "jpg",
      summary:
        'You can never have too many main course recipes, so give Roasted Cabbage Wedge Salad with Yogurt Gorgonzola Dressing a try. This recipe makes 4 servings with <b>201 calories</b>, <b>13g of protein</b>, and <b>12g of fat</b> each. For <b>$1.41 per serving</b>, this recipe <b>covers 16%</b> of your daily requirements of vitamins and minerals. This recipe from fullbellysisters.blogspot.com requires grapeseed oil, garlic, cabbage, and greek yogurt. 551 person were impressed by this recipe. From preparation to the plate, this recipe takes about <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free and primal</b> diet. Taking all factors into account, this recipe <b>earns a spoonacular score of 69%</b>, which is good. Similar recipes are <a href="https://spoonacular.com/recipes/roasted-cabbage-wedge-salad-with-yogurt-gorgonzola-dressing-1367449">Roasted Cabbage Wedge Salad with Yogurt Gorgonzola Dressing</a>, <a href="https://spoonacular.com/recipes/iceberg-wedge-salad-with-creamy-gorgonzola-dressing-392199">Iceberg Wedge Salad with Creamy Gorgonzola Dressing</a>, and <a href="https://spoonacular.com/recipes/southwestern-wedge-salad-with-green-chile-yogurt-dressing-628400">Southwestern Wedge Salad with Green Chile Yogurt Dressing</a>.',
      cuisines: [],
      dishTypes: [
        "side dish",
        "lunch",
        "salad",
        "main course",
        "main dish",
        "dinner",
      ],
      diets: ["gluten free", "primal"],
      occasions: [],
      instructions: "",
      analyzedInstructions: [],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/roasted-cabbage-wedge-salad-with-yogurt-gorgonzola-dressing-716430",
    },
  ],
};

export default data;
